### PR TITLE
Bugfix/llegal argument exception height

### PR DESCRIPTION
**Pull request by hossamCheck24**
when we try to test the application again i found this crash happen   so i open other PR  with fix could you check it please
image

### CODE REVIEW

**Comment by hossamCheck24** [comment]
@maik-mursall  could you check this please ?

**Comment by maik-mursall** [comment]
Hi @hossamCheck24,
thanks again for the PR.

Did you try to build this change to confirm it fixes your Issue?
Other than that I would like to have `fillMaxSize` even if scrolling is disabled.
But I agree that `.height(IntrinsicSize.Min)` may only be necessary if scrolling is enabled.

**Comment by enghossamelsawy** [comment]
i already insert SDK as Module and try this fix and work fine

 the problem   
 when enabling scroll false and set ` .height(IntrinsicSize.Min) ` 
 
 this what  case the crash

**Comment by maik-mursall** [comment]
@hossamCheck24 I've actually managed to reproduce the same crash :)
It occurs when you disable scroll and when you start a second session.

Means it will work perfectly for the first flow but all subsequent flows will crash.

I can confirm, that your fix works :)

**Comment by maik-mursall** [comment]
@hossamCheck24 I've released this under [v5.1.4](https://github.com/FinTecSystems/xs2a-android/releases/tag/5.1.4).

It will be available on MavenCentral within the next few hours 🎉

**Pull request merged**
