### PR TITLE
bugfix/noNetworkInfiniteLoading

### PR DESCRIPTION
**Pull request by hossamCheck24**
Fix infinite loading behavior when there is no internet and also stop calling the network when there is  no network

### CODE REVIEW

**Comment by maik-mursall** [comment]
Hello @hossamCheck24,
I'd rather have this as an option rather than having the previous behavior changed.

A new option to the config could be added, which would use your proposed behavior if enabled.

If that sounds good to you, I would implement the change and add it to this PR.

**Comment by hossamCheck24** [comment]
Hello @maik-mursall  Okey yes  please add optional  to this PR  and let  test it before it get merged  
thanks for your effort

**Comment by maik-mursall** [comment]
@hossamCheck24, I committed the change, please check if you're satisfied with it :)

**Comment by hossamCheck24** [comment]
@maik-mursall  Hi again it is look great Thanks a lot for your effort please proceed

**Comment by maik-mursall** [comment]
I released this under [v3.14.0](https://github.com/FinTecSystems/xs2a-android/releases/tag/3.14.0).
Please allow MavenCentral a few hours to process the release.

**Pull request merged**
